language: node_js
node_js:
  - "node"
  - "8"
cache:
  directories:
    - node_modules/
install:
  - npm install
  - npm install -g vuepress
script:
  - vuepress build site
deploy:
  provider: surge
  project: ./site/.vuepress/dist/
  domain: musik.surge.sh
  skip_cleanup: true